# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build Commands Service

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  commandsservice_image: "${{ secrets.DOCKER_HUB_USERNAME }}/commandsservice"
  project_image_name: "commandsservice"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create Docker Image
        run: dotnet publish ./CommandsService.csproj /t:PublishContainer -r linux-x64
      - name: Change Image Tag
        run: docker tag ${{ env.project_image_name }} ${{ env.commandsservice_image }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Push
        run: docker push ${{ env.commandsservice_image }}

  deploy:
    if: ${{ vars.DEPLOY_TO_AZURE_WEB_APP == 'true' }}
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.commandsservice_image }}
